name: Build snac2 Docker image and push to the registry

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to build container from
        required: true
        default: latest
        type: string
env:
  AUTHOR: grunfink
  NAME: snac2

jobs:
  obtain:
    runs-on: ubuntu-latest
    outputs:
      snac-ver: ${{ steps.snac-ver.outputs.snac-ver }}
    steps:
      - id: snac-url
        name: Find snac specific version
        run: |
           snac_url=`curl -s -X 'GET' 'https://codeberg.org/api/v1/repos/${{ env.AUTHOR }}/${{ env.NAME }}/tags?page=1&limit=10' -H 'accept: application/json' | jq --arg ver "{{ inputs.tag }}" \
           'map(select(.name == $ver)) as $match | 
           if ($match | length) > 0 then 
             $match[0].tarball_url 
           else 
             .[0].tarball_url 
           end' - | tr -d '"'`
           echo "url=$snac_url" >> $GITHUB_OUTPUT
      - name: Download source tarball
        run: curl -s -O ${{ steps.snac-url.outputs.url }}
      - id: snac-ver
        name: Get snac version
        run: |
          snac_ver=`echo ${{ steps.snac-url.outputs.url }} | cut -d / -f 7`
          echo "snac-ver=$snac_ver" >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snac-src
          path: ${{ steps.snac-ver.outputs.snac-ver }}
          retention-days: 1

  buildpush:
    needs: obtain
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: snac-src
    - name: Extract sources
      run: |
        tar -xzf ${{ needs.obtain.outputs.snac-ver }}
    - name: Login to GitHub packages registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build the Docker image
      run: |
        cd snac2
        docker build . --file Dockerfile --tag snac2
    - name: Push built Docker image to the registry
      run: |
        docker tag snac2 ghcr.io/${{ github.repository_owner }}/snac2:${{ inputs.tag }}
        docker push ghcr.io/${{ github.repository_owner }}/snac2:${{ inputs.tag }}
